---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Digital.ai - Official/Workflows/Secret Management
spec:
- template: Delete Secret in AWS SecretsManager
  description: Easily delete secret entries in AWS Secrets Manager.
  scheduledStartDate: 2023-09-12T03:30:00Z
  phases:
  - phase: Delete Secret
    tasks:
    - name: Create|Select AWS Secrets Manager Connection
      type: xlrelease.UserInputTask
      description: Select or create a new AWS SecretsManager connection.
      variables:
      - aws_secrets_manager
    - name: Specify Secret Details
      type: xlrelease.UserInputTask
      description: Enter the secret name to be deleted.
      variables:
      - secret_name
    - name: Delete Secret
      type: awsSecretManager.DeleteSecret
      secretName: "${secret_name}"
      description: Deletes the specified secret in the AWS SecretsManager.
      variableMapping:
        pythonScript.awsCloud: "${aws_secrets_manager}"
    color: '#3d6c9e'
  kind: WORKFLOW
  categories:
  - Cloud & Container
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/svg+xml
    file: !file "template-logo/xlr-aws-plugin.svg"
  variables:
  - type: xlrelease.ReferenceVariable
    key: aws_secrets_manager
    showOnReleaseStart: false
    label: AWS SecretsManager
    description: Connection to AWS SecretsManager
    referencedType: secrets.aws.SecretsManager
  - type: xlrelease.StringVariable
    key: secret_name
    showOnReleaseStart: false
    label: Secret Name
    description: Name of the secret
  - type: xlrelease.PasswordStringVariable
    key: secret_value
    showOnReleaseStart: false
    label: Secret Value
    description: Value of the secret as plain text or json key value map
  author: Digital.ai
  defaultTargetFolder: Digital.ai - Official/Workflow Executions
