---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Digital.ai - Official/Workflows/Secret Management
spec:
- template: Create Secret in AWS SecretsManager
  description: |-
    Easily create secrets in AWS Secrets Manager, which can again be looked up and substituted across Digital.ai Release templates and workflows.

    A Secret can be a map of key value pairs or a plain text value.
  scheduledStartDate: 2023-09-12T03:30:00Z
  phases:
  - phase: Create Secret
    tasks:
    - name: Create|Select AWS Secrets Manager Connection
      type: xlrelease.UserInputTask
      description: Select or create a new AWS SecretsManager connection.
      variables:
      - aws_secrets_manager
    - name: Specify Secret Details
      type: xlrelease.UserInputTask
      description: Enter the secret name and value. Secret value can be plain text
        or a json key value map.
      variables:
      - secret_name
      - secret_value
    - name: Create Secret
      type: awsSecretManager.SetSecret
      secretName: "${secret_name}"
      description: Creates a secret with the specified value in AWS SecretsManager.
      variableMapping:
        pythonScript.awsCloud: "${aws_secrets_manager}"
        pythonScript.secretValue: "${secret_value}"
    color: '#3d6c9e'
  kind: WORKFLOW
  categories:
  - Cloud & Container
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/svg+xml
    file: !file "template-logo/xlr-aws-plugin.svg"
  variables:
  - type: xlrelease.ReferenceVariable
    key: aws_secrets_manager
    showOnReleaseStart: false
    label: AWS SecretsManager
    description: Connection to AWS SecretsManager
    referencedType: secrets.aws.SecretsManager
  - type: xlrelease.StringVariable
    key: secret_name
    showOnReleaseStart: false
    label: Secret Name
    description: Name of the secret
  - type: xlrelease.PasswordStringVariable
    key: secret_value
    showOnReleaseStart: false
    label: Secret Value
    description: Value of the secret as plain text or json key value map
  author: Digital.ai
  defaultTargetFolder: Digital.ai - Official/Workflow Executions
